### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by jekuno** [pinittome/pinitto.me#132]
Nice app! Did you ever think about adding a "Deploy to Heroku" button to the Readme? That might help a lot to increase the user base of `pinitto.me` as Heroku users can deploy `pinitto.me` by the simple press of a button.

For details see https://devcenter.heroku.com/articles/heroku-button.

**Comment by lloydwatkin** [comment]
I hadn't, but I also don't get much time to work on the app itself. Barring some required updates (due to database upgrades, etc) its been ticking along by itself for the past few years with little/no effort.  I do mean to pick up working on it again in the future, maybe this will be part of the work :)
